<map version="1.0.1">
<!-- To view this file, download free mind mapping software FreeMind from http://freemind.sourceforge.net -->
<node CREATED="1510059491112" ID="ID_665245029" MODIFIED="1579071485222" TEXT="Architect">
<node CREATED="1510059811345" FOLDED="true" ID="ID_1798970262" MODIFIED="1552883397433" POSITION="right" TEXT="Def">
<node CREATED="1510059815366" ID="ID_1363582708" MODIFIED="1510059817437" TEXT="Requires hand-on knowledge of portfolio, applications, and application related platforms, software packages, custom components, software components and hardware requirements of the application and data in order to maintain applications-related quality, performance, availability, scalability and integrity. Responsible for ensuring the functional interface to applications and application usability continues to performs as expected. Performs ongoing architecture quality review activities relative to specific project/programs they are responsible for. Supports best practices in the critical evaluation and selection and / or development of the software components and hardware requirements of the applications and data, and the development of the application, including evaluation and selection of development methods, development processes, best practices and tools. Responsible for the functional interface to applications and for ensuring application usability."/>
</node>
<node COLOR="#338800" CREATED="1579071485104" FOLDED="true" ID="ID_919910760" MODIFIED="1579073590083" POSITION="right" TEXT="Types of Architect">
<font BOLD="true" NAME="SansSerif" SIZE="16"/>
<node CREATED="1510059830382" FOLDED="true" ID="ID_813067575" MODIFIED="1579071480033" TEXT="Business Architect">
<node CREATED="1510059848173" MODIFIED="1510059848173" TEXT="Business Architects focus on the structural and behavior-producing aspects of businesses. They address the business aspects of solutions and solution components through systemic analysis of, for example, business value, role-players, culture, components, information, processes, locations, etc. They mobilize and orchestrate IBM and third-party experts and communities of practice to provide rigorous conceptual leadership for the projects and ongoing relationships that deliver client business intent. They do this by analyzing and prescribing coordinated business and technical design decisions to deliver the promised value. Through holistic views and models they assess overlaps, dependencies, stakeholder impact, and business and technical risk across various business initiatives. They shape strategy by influencing prioritization of change initiatives in light of what is possible from both a business and technology perspective. They bridge gaps between business and IT personnel by helping the enterprise document its operational business design based on sound principles and standards. Show less"/>
</node>
<node CREATED="1510059874161" FOLDED="true" ID="ID_1551791787" MODIFIED="1579071476114" TEXT="Business Process Solution Architect">
<node CREATED="1510059901763" ID="ID_1418506476" MODIFIED="1510059901763" TEXT="The Business Process Solution Architect role is responsible for the development of the Business Process outsourcing solution that IBM offers to clients in the areas of F&amp;A, CRM, HR and SCM. This involves the development of a price competitive and innovative business process outsourcing solution that meets the client requirements and delivers value to our clients. Specific areas of focus include: Design &amp; development of a successful solution architecture - Business Process Solution Architect needs to have a clear understanding of the client&apos;s requirements and the ability to design the &quot;to be&quot; solution to meet the clients requirements. This includes process definition, solution offerings to support the processes, and the required infrastructure to implement the solution. In addition security, compliance and other solution considerations need to be addressed as part of the solution design. Development of a cost case - This involves the identification of the various cost elements, and taking a balanced approach to delivering a cost competitive solution without compromising on service delivery quality. Service level Agreements - As the engagement progresses, the Solution Architect working with the delivery team will need to participate in the negotiation of the Service Level Agreements. Development and selling of the IBM Value proposition - Developing a compelling and differentiating IBM value proposition is critical to selling the IBM solution and the Solution Architect needs to have the ability to develop and sell this during the engagement cycle. Collaboration and partnership - As a key member of the sales engagement team, the Solution Architect will need to work effectively with the client teams and with Third Party advisors and establish strong relationships. In addition, this role requires strong collaboration skills and ability to partner with various internal IBM organizations"/>
</node>
<node CREATED="1510059918490" FOLDED="true" ID="ID_694084540" MODIFIED="1579071475293" TEXT="Enterprise Architect">
<node CREATED="1510059935028" ID="ID_1054250350" MODIFIED="1577775931501" TEXT="This role defines a high level enterprise-wide IT Architecture focusing on the mapping of I/T capabilities to business needs."/>
<node CREATED="1577775934167" ID="ID_881896524" MODIFIED="1577775934167" TEXT="defining the relationships, flows and implementation of business (processes/activities/functions, information), applications, data and technology in the enterprise and the transitional process necessary for implementing technology in response to changing business needs"/>
</node>
<node CREATED="1510059952238" FOLDED="true" ID="ID_1025853644" MODIFIED="1511183986406" TEXT="Information Architect">
<node CREATED="1510059963623" MODIFIED="1510059963623" TEXT="This role focuses on the elements required to manage all aspects of data and information (both structured and unstructured) from business requirements to logical and physical design. This role spans the full information management lifecycle from acquisition, through cleanse, transform, classify and storage to presentation, distribution, security, privacy and archiving. The key interests of the Information Architect include databases (relational, hierarchical and object-oriented), file systems and storage management, as well as document imaging, knowledge and content management, taxonomies and business intelligence. Information Architects must be capable of designing centralized or distributed systems that both address the user&apos;s requirements and perform efficiently and effectively."/>
</node>
<node CREATED="1510059977692" FOLDED="true" ID="ID_472246447" MODIFIED="1579071474443" TEXT="Infrastructure Architect">
<node CREATED="1510059984584" MODIFIED="1510059984584" TEXT="This role concentrates on the design of infrastructures including servers, storage, workstations, middleware, non-application software, networks, and the physical facilities that support the applications and business processes required by the client. Included in the focus areas is the critical evaluation and selection of the software and hardware components of the infrastructure. Best practices in this role use various techniques including modeling, simulation, and testing to validate the designs and selected products. Infrastructure Architects are responsible for performance, availability and scalability of the infrastructure."/>
</node>
<node CREATED="1510059999127" FOLDED="true" ID="ID_593777119" MODIFIED="1579071473469" TEXT="Integration Architect">
<node CREATED="1510060005618" ID="ID_1062170576" MODIFIED="1510060005618" TEXT="This role is focused on the design of solutions which enable existing and new application components, existing and new applications, packaged software offerings and systems to work together within an enterprise or among enterprises. These solutions may use different technologies, vendors, platforms, and styles of computing. The primary focus of an Integration Architect is to develop solutions that fully integrate and collaborate with existing IT systems in order to perform an automated business function (usually known as &quot;Enterprise Application Integration&quot; or more recently as &quot;Business Integration&quot;). New Services Oriented Architectures (SOA), the related standards and technologies are an important area for this role. All levels of integration are within the scope of the Integration Architect (User Access, Application, Extended Enterprise, Process, and Information Integration). Integration Architect requires a holistic view of enterprise solutions, including a sound appreciation of operational costs, security, performance engineering, application development and systems management."/>
</node>
<node CREATED="1510060098459" FOLDED="true" ID="ID_206771895" MODIFIED="1579071477688" TEXT="Technical Solution Architect">
<node CREATED="1510060111261" ID="ID_1886975063" MODIFIED="1510060111261" TEXT="This role assumes overall technical responsibility for the success of solution construction, implementation and system integration in a technology, industry or business specialty. They deliver new and complex high quality solutions to clients in response to varying business requirements. They utilize in-depth knowledge of leading-edge products and technology in conjunction with industry and business skills to influence clients."/>
</node>
<node CREATED="1510060034321" FOLDED="true" ID="ID_1497048166" MODIFIED="1510060154273" TEXT="Operations Architect">
<node CREATED="1510060044672" MODIFIED="1510060044672" TEXT="This role&apos;s best practices center on the design of systems to manage the infrastructure and applications used by the client. This role focuses on defining plans, strategies and architectures for the installation, operation, migration and management of complex information systems. An Operations Architect gathers and analyzes client I/T needs, translates these needs into requirements for specific systems management processes, products, and services, and may lead or advise the teams which install, operate and maintain the I/T system"/>
</node>
<node CREATED="1510060062778" FOLDED="true" ID="ID_1362556570" MODIFIED="1510060156965" TEXT="Security Architect">
<node CREATED="1510060077563" MODIFIED="1510060077563" TEXT="The Security Architect role focuses on the design of business-driven Information Technology solutions to meet security requirements related to function, protection, assurance, risk management and compliance. The scope of work includes: (1) the collection and validation of requirements, (2) the identification of risks, threats, vulnerabilities, potential anomalous flows and interactions, (3) the definition of the security processes for assurance, management and compliance, (4) the definition of security subsystems, and (5) the design of integration and deployment architectures for security in Networks, Infrastructure, Middleware, Applications and Systems &amp; Service Management systems. Depending on the area of work, the Security Architect may perform evaluation and selection of the components, design of hardware, software, process and service components of the solution, assurance of deployment architectures, and guide secure engineering practices in development."/>
</node>
<node CREATED="1510060127253" FOLDED="true" ID="ID_199851016" MODIFIED="1510060159457" TEXT="Test Architect">
<node CREATED="1510060143361" MODIFIED="1510060143361" TEXT="This role is usually performed by a senior Application Architect specializing in the testing of applications or solutions. They are responsible for designing test strategy, setting the direction for testing, and recommending test tools. They provide technical leadership and assist the Test Manager with test planning. They provide leadership for test design and guidance during test specification development. They act as a mentor and coach, participates in team meetings, and creates Intellectual Capital assets for reuse"/>
</node>
<node CREATED="1510060016319" ID="ID_1795945465" MODIFIED="1510060017731" TEXT="Interface Architect"/>
<node CREATED="1510060026291" ID="ID_286398086" MODIFIED="1510060027786" TEXT="Network Integration Architect"/>
<node CREATED="1510060056853" ID="ID_1854418039" MODIFIED="1510060058034" TEXT="Private Cloud Architect"/>
</node>
<node CREATED="1579071492556" ID="ID_900487177" MODIFIED="1579073413575" POSITION="right" TEXT="97 things to know">
<font BOLD="true" NAME="SansSerif" SIZE="16"/>
<node CREATED="1579071812608" MODIFIED="1579071812608" TEXT="It&#x2019;s the duty of the architect to solve the problems inherent in    essential complexity without introducing accidental complexity."/>
<node CREATED="1579072031679" MODIFIED="1579072031679" TEXT="If you start with a shared purpose, treat people &#x201c;problems&#x201d; as an    opportunity to learn, and manage your own emotions, you&#x2019;ll not only become    more effective, you&#x2019;ll also discover that you learn something every    time."/>
<node CREATED="1579072393042" ID="ID_947895361" MODIFIED="1579072415108" TEXT="Keeping developers in the dark about the big picture or why decisions were made is a clear recipe for disaster. Having the developer on your side creates a collaborative environment whereby decisions you make as an architect are validated"/>
<node CREATED="1579073414381" ID="ID_1343363892" MODIFIED="1579073414381" TEXT="Seek the Value in Requested Capabilities"/>
<node CREATED="1579073588454" ID="ID_1120021018" MODIFIED="1579073597169" TEXT="Stand-up">
<font BOLD="true" NAME="SansSerif" SIZE="16"/>
<node CREATED="1579073646418" MODIFIED="1579073646418" TEXT="If you&#x2019;re in any situation where you&#x2019;re talking to more than one person about your guidance, stand up. Whether it&#x2019;s a formal design review, or an informal discussion over some diagrams, it doesn&#x2019;t matter. Stand up, especially if everyone else is sitting down."/>
</node>
<node CREATED="1579074437043" ID="ID_470724976" MODIFIED="1579074469829" TEXT="Michael Nygard - Everything Will Ultimately Fail">
<font BOLD="true" NAME="SansSerif" SIZE="16"/>
<node CREATED="1579074440870" ID="ID_1393877728" MODIFIED="1579074447460" TEXT="design for failuers"/>
</node>
<node CREATED="1579075675599" ID="ID_1318115082" MODIFIED="1579075686362" TEXT="Keith Braithwaite - Quantify">
<font BOLD="true" NAME="SansSerif" SIZE="16"/>
<node CREATED="1579075791384" MODIFIED="1579075791384" TEXT="Uncertain quantitative criteria must be given as a range: the least, the nominal, and the most."/>
</node>
</node>
</node>
</map>
